[project]
name = "sabreu-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
test = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
]
dev = [
    "ruff>=0.11.1",
]
